### PR TITLE
773 Fix: jQuery is not a function

### PR DESCRIPTION
**Pull request by leonstr**
Fix error in browser console error which occurs with Moodle 4.5 on plugin settings page (plagiarism/turnitin/settings.php).

This seems to work correctly with Moodle 4.4 too.

### CODE REVIEW

**Review by jack-tii — APPROVED** [review]
I was about to put up the same fix, you beat me to it by about 5 minutes
Thanks!
